.docker-windows-base-matrix:
  parallel:
    matrix:
      - DISTRIBUTION_NAME: windows
        DISTRIBUTION_VERSION: "1809"
        DISTRIBUTION_BASE_IMAGE: mcr.microsoft.com/windows:1809@sha256:1563bf154c361fc62ce5a082d8cd149d19fef59744bdbc7f836d719616e24b49
      - DISTRIBUTION_NAME: windows
        DISTRIBUTION_VERSION: "1809"
        DISTRIBUTION_BASE_IMAGE: mcr.microsoft.com/windows:1809
      - DISTRIBUTION_NAME: windows
        DISTRIBUTION_VERSION: "2004"
        DISTRIBUTION_BASE_IMAGE: mcr.microsoft.com/windows:2004
      - DISTRIBUTION_NAME: ubuntu
        DISTRIBUTION_VERSION: "latest"
        DISTRIBUTION_BASE_IMAGE: ubuntu:latest
      - DISTRIBUTION_NAME: ubuntu
        DISTRIBUTION_VERSION: "bionic"
        DISTRIBUTION_BASE_IMAGE: ubuntu:bionic
